# freecodecamp-numpy-review

Use the "Run" button to execute the code.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [ ]:
# Execute this to save new versions of the notebook
jovian.commit(project="freecodecamp-numpy-review")

<IPython.core.display.Javascript object>

In [4]:
import numpy as np

## The Basics

In [22]:
a = np.array([1,2,3], dtype='int32') # Specifying a smaller data type takes up less resources/space
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# Get the dimension
a.ndim

1

In [13]:
# Get shape
b.shape

(2, 3)

In [14]:
a.shape

(3,)

In [18]:
# Get type
a.dtype

dtype('int64')

In [21]:
# Get size
a.itemsize

4

In [23]:
# Total size
a.nbytes

12

## Accessing/Changing specific elements, rows, columns

In [26]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Get a specific element [r, c]
a[1,5]

13

In [30]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [32]:
# Getting more fancy [startindex: endindex: stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [41]:
# 3D example
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# get specific element (work outside in)
# grab 4
b[0,1,1]

4

In [44]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [46]:
# All zeroes matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [51]:
# Any other number (takes two arguments)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [53]:
# Any other number (full like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Random decimal number matrix
np.random.rand(4,2,3)

array([[[0.63255293, 0.06954302, 0.01306585],
        [0.48651738, 0.74493784, 0.61210147]],

       [[0.68481977, 0.05893508, 0.8336935 ],
        [0.03220888, 0.72239109, 0.22893288]],

       [[0.40244597, 0.18039789, 0.53320498],
        [0.21519742, 0.84831799, 0.69943603]],

       [[0.88094575, 0.02892395, 0.55626824],
        [0.7456255 , 0.43285775, 0.75619682]]])

In [57]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[3, 4, 5],
       [6, 0, 2],
       [0, 0, 4]])

In [60]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [79]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [91]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [92]:
a + 2
print(a)

[1 2 3 4]


In [83]:
a - 2

array([-1,  0,  1,  2])

In [84]:
a * 2

array([2, 4, 6, 8])

In [85]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [93]:
a ** 2

array([ 1,  4,  9, 16])

In [94]:
# Take the sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [95]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [104]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [106]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [107]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
np.min(stats)

1

In [109]:
np.min(stats, axis=1)

array([1, 4])

In [111]:
np.max(stats, axis=1)

array([3, 6])

In [112]:
np.sum(stats)

21

In [115]:
np.sum(stats,axis=0) # sum of columns

array([5, 7, 9])

#### Reorganizaing Arrays

In [120]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [122]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [126]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [137]:
a = np.arange(1,31)
b = a.reshape(6,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [138]:
b[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [141]:
b[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [142]:
b[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])