> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Numpy Array Operations You NEED to Know



NumPy is the foundational scientific computing pakcage that utilizes Python. It allows users to create vectors and matrices of data that can be manipulated along with mathematical operations and statistics, very commonly used within the Data Science field. This list of five functions are crucial to using NumPy to its fullest potential, ranging from creating arrays and matrices to complex mathematical operations. Numpy arrays are more highly optimized than Python lists and utilize less computer memory and resources.

- numpy.array
- numpy.reshape
- numpy.arange
- numpy.split
- numpy.insert

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "aciorra83/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/aciorra83/numpy-array-operations


'https://jovian.ai/aciorra83/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.array
function2 = np.reshape
function3 = np.arange
function4 = np.split
function5 = np.insert

## Function 1 - np.array

You gotta start somewhere, numpy.array allow you to create arrays

In [6]:
# Example 1 - working
arr1 = np.array([1,2,3,4])
print(arr1)
np.array('Hello')

[1 2 3 4]


array('Hello', dtype='<U5')

Example 1: The np.array() function takes a list as its argument and returns an array. Running 'arr1' in our Jupyter notebook cell will return what data type arr1 is to verify that it is indeed an array. Additionally, we can use other data types such as strings within our arrays like with our "Hello" array.

In [7]:
arr1

array([1, 2, 3, 4])

In [8]:
# Example 2 - working
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


Example 2: We've created two sub arrays by adding an extra set of [ ] brackets around our two other lists passed in as arguments. 

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
np.array()

TypeError: array() missing required argument 'object' (pos 1)

Example 3: this function will produce an error whenever there is no argument passed into the function. The error message will display that it is missing a REQUIRED argument object. 

Using the numpy.array() function is useful when working with smaller arrays that you want to create by hand rather than a large data set. 

In [10]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "aciorra83/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/aciorra83/numpy-array-operations


'https://jovian.ai/aciorra83/numpy-array-operations'

## Function 2 - Numpy.reshape

Gives your array new dimensions without changing the data inside

In [11]:
# Example 1 - working
x = np.array([1,2,3,4,5,6])
print(x)

x.reshape(3,2)

[1 2 3 4 5 6]


array([[1, 2],
       [3, 4],
       [5, 6]])

Example 1: We've created a one dimensional array with numbers 1-6, but we want a 3x2 (3 rows and 2 columns) two dimensional array. In order to reshape array 'x' we use the reshape function with the desired parameters passed in as arguments.

In [12]:
# Example 2 - working
z = np.array([1,2,3,4,5,6])

z.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Example 3: In this example our array has now split each value into nested arrays with one value in a single column, you can continue to nest arrays like so:

In [13]:
z.reshape(6,1,1,1)

array([[[[1]]],


       [[[2]]],


       [[[3]]],


       [[[4]]],


       [[[5]]],


       [[[6]]]])

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
z.reshape(20,3)

ValueError: cannot reshape array of size 6 into shape (20,3)

Example 3: In our final example we see that our new dimensions 20 rows by 3 columns for our array of 6 values will not work. We don't have enough values to fill an array of that size and NumPy will not create values to fill, instead it will raise an array stating that it is unable to reshape. 

Reshaping is very useful when working with multiple data sets, uniformity is extremely beneficial when working in NumPy when it comes to calculations and the reshape function gives the user a tool to do so. 

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "aciorra83/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/aciorra83/numpy-array-operations


'https://jovian.ai/aciorra83/numpy-array-operations'

## Function 3 - Numpy.arange

Return even spaced values within a given range of numbers

In [27]:
# Example 1 - working
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Numpy.arange takes either integers or floats as arguments and returns the specified number of values evenly spaced. In the above example, we see that in one line we can quickly create an array with 100 values.

In [18]:
# Example 2 - working
np.arange(0,6,2)

array([0, 2, 4])

In example 2, there are three arguments passed into the np.arange function. The order of arguments passed are np.arange(start, stop, step). Meaning that the vector starts at value 0, goes up to but does not include 6 and increments by 2 every iteration. 

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(0,6,2,5)

TypeError: Cannot interpret '5' as a data type

Example 3 shows that the first three arguments passed into the np.arange function can only be integers or floats. If a fourth value is passed in as an argument it will raise an error. Instead, the fourth argument should be a data type such as int or float in the example below. 

In [29]:
np.arange(0,6,2, dtype=float)

array([0., 2., 4.])

The arange function is useful for creating large arrays quickly and efficiently, rather than constructing by each value like you would with the np.array method. 

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "aciorra83/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/aciorra83/numpy-array-operations


'https://jovian.ai/aciorra83/numpy-array-operations'

## Function 4 - Numpy.split

Split an array into multiple arrays : 
numpy.split(ary, indices_or_sections, axis=0)

In [36]:
# Example 1 - working
z = np.arange(9)
np.split(z,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In example 1 the array is creating with 0 values, we use the split method to divid them into equal groups of 3 sub arrays.

In [46]:
# Example 2 - working
x = np.arange(10)
np.split(x, [2,3,4])

[array([0, 1]), array([2]), array([3]), array([4, 5, 6, 7, 8, 9])]

Example 2 shows the results when another array is passed in as the second argument. Our output shows the same as if we were to index x[0:2] and then x[3], x[4] and lastly x[4:0].

In [47]:
# Example 3 - breaking (to illustrate when it breaks)
z = np.arange(9)
np.split(z,5)

ValueError: array split does not result in an equal division

In our final example we see that if the indices_or_sections argument is not evenly divisible by the number of values within the array we receive an error message traceback.

This method is useful anytime you'd like to break your data into smaller chunks, it can help you to recognize patterns or even outlier values within your dataset. 

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "aciorra83/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/aciorra83/numpy-array-operations


'https://jovian.ai/aciorra83/numpy-array-operations'

## Function 5 - Numpy.insert

Insert values along the given axis before the given indices: numpy.insert(arr, obj, values, axis=None)

In [51]:
# Example 1 - working
a = np.array([1,1,1])
print(a)

np.insert(a,1,2)


[1 1 1]


array([1, 2, 1, 1])

In example one we have taken array 'a' and just before index position 1 we are inserting the number 2.

In [68]:
# Example 2 - working
a = np.array([[1,1],[2,2],[3,3]])
print(np.insert(a,1,5,axis=0))
print()
print(np.insert(a,1,5,axis=1))

[[1 1]
 [5 5]
 [2 2]
 [3 3]]

[[1 5 1]
 [2 5 2]
 [3 5 3]]


The above exmaple shows a two dimensional array and when passing in the axis argument into the method we are able to add an additional row for axis=0 and an additional column with axis=1 at the index before the specified value of 5. 

In [70]:
# Example 3 - breaking (to illustrate when it breaks)
np.insert(a,1,5,axis=3)

AxisError: axis 3 is out of bounds for array of dimension 2

In our final example we break the code by setting the axis argument as axis=3. In a two dimensional array the only axis values are 1 or 0, any other axis simply do not exist and are out of bounds as the error message states. 

Anytime you need to add values within your array you'll be utilizing numpy.insert

In [71]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "aciorra83/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/aciorra83/numpy-array-operations


'https://jovian.ai/aciorra83/numpy-array-operations'

## Conclusion

In this notebook we cover 5 essential Numpy tools to add to your data science toolbelt that allow you to manipulate and transform arrays:
- numpy.array
- numpy.reshape
- numpy.arange
- numpy.split
- numpy.insert

Once you feel comfortable with these methods, you should work through the Numpy documentation tutorials found here  https://numpy.org/doc/stable/user/quickstart.html. After that you will have a solid understanding of 2 dimensional arrays and can begin working with the Pandas Python library to further your understanding of NEED to know Python libraries for data science.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>